# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      automountServiceAccountToken: false
      containers:
        - name: user-service

          image: 878445923420.dkr.ecr.us-east-1.amazonaws.com/user-service:1.0.0

          ports:
            - containerPort: 3001

          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
              ephemeral-storage: "1Gi"

            limits:
              memory: "256Mi"
              cpu: "500m"
              ephemeral-storage: "2Gi"