# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service

type: Opaque

stringData:
  DB_USER: postgres
  DB_PASSWORD: ChangeMe123!
  JWT_SECRET: supersecretjwt