name : Deploy java Application

on:
    push:
       branches:
         - Dev01

jobs:
    deploy:
         runs-on : ubuntu-latest

         steps:
            - uses: actions/checkout@v3
            
            - name: Setup Java 17
              uses: actions/setup-java@v4
              with:
               distribution: temurin
               java-version: '17'
               cache: maven

            - name : Build
              run : mvn clean package -f Java-Login-App/pom.xml

            - name: Check target folder
              working-directory: Java-Login-App
              run: ls -l target


            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Upload JAR
              working-directory : Java-Login-App
              run: aws s3 cp target/*jar s3://cloud-bucket-1770975946/app.jar

            - name: Terraform Init
              run: terraform init
              working-directory: terraform

            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: terraform